/*DROP TABLE IF EXISTS hobby;
create table hobby (
                        id varchar (1000),
                        name  varchar(255),
                       description  varchar(255),
                       category varchar(255),
                        environment varchar(255),
                        PRIMARY KEY (id)


);*/
/*
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'3D printing','https://en.wikipedia.org/wiki/3D_printing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Acrobatics','https://en.wikipedia.org/wiki/Acrobatics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Acting','https://en.wikipedia.org/wiki/Acting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Amateur radio','https://en.wikipedia.org/wiki/Amateur_radio','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Animation','https://en.wikipedia.org/wiki/Animation','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Aquascaping','https://en.wikipedia.org/wiki/Aquascaping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Astrology','https://en.wikipedia.org/wiki/Astrology','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Baking','https://en.wikipedia.org/wiki/Baking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Baton twirling','https://en.wikipedia.org/wiki/Baton_twirling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Blogging','https://en.wikipedia.org/wiki/Blogging','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Board game','https://en.wikipedia.org/wiki/Board_game','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Book discussion club','https://en.wikipedia.org/wiki/Book_discussion_club','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Book restoration','https://en.wikipedia.org/wiki/Book_restoration','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Bowling','https://en.wikipedia.org/wiki/Bowling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Brazilian jiu-jitsu','https://en.wikipedia.org/wiki/Brazilian_jiu-jitsu','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Breadmaking','https://en.wikipedia.org/wiki/Breadmaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Building','https://en.wikipedia.org/wiki/Building','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Bullet Journal','https://en.wikipedia.org/wiki/Bullet_Journal','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cabaret','https://en.wikipedia.org/wiki/Cabaret','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Calligraphy','https://en.wikipedia.org/wiki/Calligraphy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Candle making','https://en.wikipedia.org/wiki/Candle_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Candy making','https://en.wikipedia.org/wiki/Candy_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Car','https://en.wikipedia.org/wiki/Car','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Card games','https://en.wikipedia.org/wiki/Card_games','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cardistry','https://en.wikipedia.org/wiki/Cardistry','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cheesemaking','https://en.wikipedia.org/wiki/Cheesemaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cleaning','https://en.wikipedia.org/wiki/Cleaning','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Clothing','https://en.wikipedia.org/wiki/Clothing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Home roasting coffee','https://en.wikipedia.org/wiki/Home_roasting_coffee','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Collecting','https://en.wikipedia.org/wiki/Collecting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Coloring book','https://en.wikipedia.org/wiki/Coloring_book','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Computer programming','https://en.wikipedia.org/wiki/Computer_programming','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Confectionery','https://en.wikipedia.org/wiki/Confectionery','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cooking','https://en.wikipedia.org/wiki/Cooking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cosplaying','https://en.wikipedia.org/wiki/Cosplaying','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Couponing','https://en.wikipedia.org/wiki/Couponing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Craft','https://en.wikipedia.org/wiki/Craft','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Creative writing','https://en.wikipedia.org/wiki/Creative_writing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Crocheting','https://en.wikipedia.org/wiki/Crocheting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cross-stitch','https://en.wikipedia.org/wiki/Cross-stitch','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Crossword puzzles','https://en.wikipedia.org/wiki/Crossword_puzzles','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cryptography','https://en.wikipedia.org/wiki/Cryptography','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cue sports','https://en.wikipedia.org/wiki/Cue_sports','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Dance','https://en.wikipedia.org/wiki/Dance','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Digital art','https://en.wikipedia.org/wiki/Digital_art','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Distro-hopping','https://en.wikipedia.org/wiki/Distro-hopping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Disc-jockey','https://en.wikipedia.org/wiki/Disc-jockey','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Do it yourself','https://en.wikipedia.org/wiki/Do_it_yourself','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Drama','https://en.wikipedia.org/wiki/Drama','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Drawing','https://en.wikipedia.org/wiki/Drawing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mixed drink','https://en.wikipedia.org/wiki/Mixed_drink','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Drinking','https://en.wikipedia.org/wiki/Drinking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Electronic games','https://en.wikipedia.org/wiki/Electronic_games','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Electronics','https://en.wikipedia.org/wiki/Electronics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Embroidery','https://en.wikipedia.org/wiki/Embroidery','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Experimenting','https://en.wikipedia.org/wiki/Experimenting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fantasy sport','https://en.wikipedia.org/wiki/Fantasy_sport','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fashion','https://en.wikipedia.org/wiki/Fashion','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fashion design','https://en.wikipedia.org/wiki/Fashion_design','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fishkeeping','https://en.wikipedia.org/wiki/Fishkeeping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Filmmaking','https://en.wikipedia.org/wiki/Filmmaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Flower arranging','https://en.wikipedia.org/wiki/Flower_arranging','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fly tying','https://en.wikipedia.org/wiki/Fly_tying','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Second-language acquisition','https://en.wikipedia.org/wiki/Second-language_acquisition','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Furniture','https://en.wikipedia.org/wiki/Furniture','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Games','https://en.wikipedia.org/wiki/Games','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tabletop game','https://en.wikipedia.org/wiki/Tabletop_game','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Role-playing game','https://en.wikipedia.org/wiki/Role-playing_game','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Genealogy','https://en.wikipedia.org/wiki/Genealogy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Gingerbread house','https://en.wikipedia.org/wiki/Gingerbread_house','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Glassblowing','https://en.wikipedia.org/wiki/Glassblowing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Graphic design','https://en.wikipedia.org/wiki/Graphic_design','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Gunsmithing','https://en.wikipedia.org/wiki/Gunsmithing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Gymnastics','https://en.wikipedia.org/wiki/Gymnastics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hacker','https://en.wikipedia.org/wiki/Hacker','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Herpetoculture','https://en.wikipedia.org/wiki/Herpetoculture','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Home improvement','https://en.wikipedia.org/wiki/Home_improvement','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Homebrewing','https://en.wikipedia.org/wiki/Homebrewing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Houseplant care','https://en.wikipedia.org/wiki/Houseplant_care','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hula hooping','https://en.wikipedia.org/wiki/Hula_hooping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Humor','https://en.wikipedia.org/wiki/Humor','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hydroponics','https://en.wikipedia.org/wiki/Hydroponics','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ice skating','https://en.wikipedia.org/wiki/Ice_skating','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Jewelry making','https://en.wikipedia.org/wiki/Jewelry_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Jigsaw puzzles','https://en.wikipedia.org/wiki/Jigsaw_puzzles','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Diary','https://en.wikipedia.org/wiki/Diary','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Juggling','https://en.wikipedia.org/wiki/Juggling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Karaoke','https://en.wikipedia.org/wiki/Karaoke','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Karate','https://en.wikipedia.org/wiki/Karate','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Kendama','https://en.wikipedia.org/wiki/Kendama','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Knife making','https://en.wikipedia.org/wiki/Knife_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Knitting','https://en.wikipedia.org/wiki/Knitting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Knot tying','https://en.wikipedia.org/wiki/Knot_tying','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Kombucha','https://en.wikipedia.org/wiki/Kombucha','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Lace making','https://en.wikipedia.org/wiki/Lace_making','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Lapidary','https://en.wikipedia.org/wiki/Lapidary','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Leather crafting','https://en.wikipedia.org/wiki/Leather_crafting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Lego','https://en.wikipedia.org/wiki/Lego','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Music','https://en.wikipedia.org/wiki/Music','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Podcasts','https://en.wikipedia.org/wiki/Podcasts','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Lock picking','https://en.wikipedia.org/wiki/Lock_picking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Machining','https://en.wikipedia.org/wiki/Machining','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Macrame','https://en.wikipedia.org/wiki/Macrame','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Magic (illusion)','https://en.wikipedia.org/wiki/Magic_(illusion)','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Makeup','https://en.wikipedia.org/wiki/Makeup','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Maze','https://en.wikipedia.org/wiki/Maze','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Metalworking','https://en.wikipedia.org/wiki/Metalworking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Model building','https://en.wikipedia.org/wiki/Model_building','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Model engineering','https://en.wikipedia.org/wiki/Model_engineering','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Nail art','https://en.wikipedia.org/wiki/Nail_art','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Needlepoint','https://en.wikipedia.org/wiki/Needlepoint','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Origami','https://en.wikipedia.org/wiki/Origami','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Painting','https://en.wikipedia.org/wiki/Painting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Palmistry','https://en.wikipedia.org/wiki/Palmistry','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pet adoption','https://en.wikipedia.org/wiki/Pet_adoption','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Philately','https://en.wikipedia.org/wiki/Philately','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Photography','https://en.wikipedia.org/wiki/Photography','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pilates','https://en.wikipedia.org/wiki/Pilates','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Music','https://en.wikipedia.org/wiki/Music','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Poi (performance art)','https://en.wikipedia.org/wiki/Poi_(performance_art)','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pole Dancing (page does not exist)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pottery','https://en.wikipedia.org/wiki/Pottery','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Powerlifting','https://en.wikipedia.org/wiki/Powerlifting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Practical jokes','https://en.wikipedia.org/wiki/Practical_jokes','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pressed flower craft','https://en.wikipedia.org/wiki/Pressed_flower_craft','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Puzzle','https://en.wikipedia.org/wiki/Puzzle','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Quilling','https://en.wikipedia.org/wiki/Quilling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Quilting','https://en.wikipedia.org/wiki/Quilting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Quizzes','https://en.wikipedia.org/wiki/Quizzes','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Radio-controlled model','https://en.wikipedia.org/wiki/Radio-controlled_model','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rail transport modeling','https://en.wikipedia.org/wiki/Rail_transport_modeling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rapping','https://en.wikipedia.org/wiki/Rapping','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Reading','https://en.wikipedia.org/wiki/Reading','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Refinishing','https://en.wikipedia.org/wiki/Refinishing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Reiki','https://en.wikipedia.org/wiki/Reiki','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Robot combat','https://en.wikipedia.org/wiki/Robot_combat','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rubiks Cube','https://en.wikipedia.org/wiki/Rubik%27s_Cube','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Scrapbooking','https://en.wikipedia.org/wiki/Scrapbooking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'SCUBA Diving','https://en.wikipedia.org/wiki/SCUBA_Diving','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sculpting','https://en.wikipedia.org/wiki/Sculpting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sewing','https://en.wikipedia.org/wiki/Sewing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shoemaking','https://en.wikipedia.org/wiki/Shoemaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Singing','https://en.wikipedia.org/wiki/Singing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sketch (drawing)','https://en.wikipedia.org/wiki/Sketch_(drawing)','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Skipping rope','https://en.wikipedia.org/wiki/Skipping_rope','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Slot car','https://en.wikipedia.org/wiki/Slot_car','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Soapmaking','https://en.wikipedia.org/wiki/Soapmaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Social media','https://en.wikipedia.org/wiki/Social_media','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Spreadsheets','https://en.wikipedia.org/wiki/Spreadsheets','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Stand-up comedy','https://en.wikipedia.org/wiki/Stand-up_comedy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Stamp collecting','https://en.wikipedia.org/wiki/Stamp_collecting','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Table tennis','https://en.wikipedia.org/wiki/Table_tennis','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tarot','https://en.wikipedia.org/wiki/Tarot','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Taxidermy','https://en.wikipedia.org/wiki/Taxidermy','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Charity shop','https://en.wikipedia.org/wiki/Charity_shop','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Video editing','https://en.wikipedia.org/wiki/Video_editing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Video game development','https://en.wikipedia.org/wiki/Video_game_development','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Video gaming','https://en.wikipedia.org/wiki/Video_gaming','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Videography','https://en.wikipedia.org/wiki/Videography','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Virtual reality','https://en.wikipedia.org/wiki/Virtual_reality','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Movies','https://en.wikipedia.org/wiki/Movies','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Television program','https://en.wikipedia.org/wiki/Television_program','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Waxing','https://en.wikipedia.org/wiki/Waxing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Weaving','https://en.wikipedia.org/wiki/Weaving','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Webtoon','https://en.wikipedia.org/wiki/Webtoon','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Weight training','https://en.wikipedia.org/wiki/Weight_training','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Welding','https://en.wikipedia.org/wiki/Welding','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Whittling','https://en.wikipedia.org/wiki/Whittling','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Help:Editing','https://en.wikipedia.org/wiki/Help:Editing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Winemaking','https://en.wikipedia.org/wiki/Winemaking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Wood carving','https://en.wikipedia.org/wiki/Wood_carving','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Woodworking','https://en.wikipedia.org/wiki/Woodworking','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Word searches','https://en.wikipedia.org/wiki/Word_searches','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Worldbuilding','https://en.wikipedia.org/wiki/Worldbuilding','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Writing','https://en.wikipedia.org/wiki/Writing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Yo-yoing','https://en.wikipedia.org/wiki/Yo-yoing','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Yoga','https://en.wikipedia.org/wiki/Yoga','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Zumba','https://en.wikipedia.org/wiki/Zumba','Ukategoriserede hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Air sports','https://en.wikipedia.org/wiki/Air_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Airsoft','https://en.wikipedia.org/wiki/Airsoft','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Amateur geology','https://en.wikipedia.org/wiki/Amateur_geology','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Amusement park','https://en.wikipedia.org/wiki/Amusement_park','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Archery','https://en.wikipedia.org/wiki/Archery','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Astronomy','https://en.wikipedia.org/wiki/Astronomy','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Backpacking (wilderness)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Badminton','https://en.wikipedia.org/wiki/Badminton','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'BASE jumping','https://en.wikipedia.org/wiki/BASE_jumping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Baseball','https://en.wikipedia.org/wiki/Baseball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Basketball','https://en.wikipedia.org/wiki/Basketball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Beekeeping','https://en.wikipedia.org/wiki/Beekeeping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Birdwatching','https://en.wikipedia.org/wiki/Birdwatching','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Blacksmithing','https://en.wikipedia.org/wiki/Blacksmithing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'BMX','https://en.wikipedia.org/wiki/BMX','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Board sports','https://en.wikipedia.org/wiki/Board_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Bodybuilding','https://en.wikipedia.org/wiki/Bodybuilding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Bonsai','https://en.wikipedia.org/wiki/Bonsai','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Butterfly watching','https://en.wikipedia.org/wiki/Butterfly_watching','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Bus','https://en.wikipedia.org/wiki/Bus','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Camping','https://en.wikipedia.org/wiki/Camping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Canoeing','https://en.wikipedia.org/wiki/Canoeing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Canyoning','https://en.wikipedia.org/wiki/Canyoning','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Car','https://en.wikipedia.org/wiki/Car','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Caving','https://en.wikipedia.org/wiki/Caving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Composting','https://en.wikipedia.org/wiki/Composting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cycling','https://en.wikipedia.org/wiki/Cycling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Dowsing','https://en.wikipedia.org/wiki/Dowsing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Driving','https://en.wikipedia.org/wiki/Driving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Farming','https://en.wikipedia.org/wiki/Farming','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fishing','https://en.wikipedia.org/wiki/Fishing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Flag football','https://en.wikipedia.org/wiki/Flag_football','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Flower','https://en.wikipedia.org/wiki/Flower','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Aviation','https://en.wikipedia.org/wiki/Aviation','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Flying disc','https://en.wikipedia.org/wiki/Flying_disc','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Foraging','https://en.wikipedia.org/wiki/Foraging','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fossicking','https://en.wikipedia.org/wiki/Fossicking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Freestyle football','https://en.wikipedia.org/wiki/Freestyle_football','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Gardening','https://en.wikipedia.org/wiki/Gardening','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Geocaching','https://en.wikipedia.org/wiki/Geocaching','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ghost hunting','https://en.wikipedia.org/wiki/Ghost_hunting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Gold prospecting','https://en.wikipedia.org/wiki/Gold_prospecting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Graffiti','https://en.wikipedia.org/wiki/Graffiti','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Handball','https://en.wikipedia.org/wiki/Handball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Herbalism','https://en.wikipedia.org/wiki/Herbalism','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Herping','https://en.wikipedia.org/wiki/Herping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'High-power rocketry','https://en.wikipedia.org/wiki/High-power_rocketry','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hiking','https://en.wikipedia.org/wiki/Hiking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hobby horse','https://en.wikipedia.org/wiki/Hobby_horse','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hobby tunneling','https://en.wikipedia.org/wiki/Hobby_tunneling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hooping','https://en.wikipedia.org/wiki/Hooping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Horseback riding','https://en.wikipedia.org/wiki/Horseback_riding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hunting','https://en.wikipedia.org/wiki/Hunting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Inline skating','https://en.wikipedia.org/wiki/Inline_skating','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Jogging','https://en.wikipedia.org/wiki/Jogging','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Jumping rope','https://en.wikipedia.org/wiki/Jumping_rope','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Kayaking','https://en.wikipedia.org/wiki/Kayaking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Kite','https://en.wikipedia.org/wiki/Kite','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Kitesurfing','https://en.wikipedia.org/wiki/Kitesurfing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Lacrosse','https://en.wikipedia.org/wiki/Lacrosse','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'LARPing','https://en.wikipedia.org/wiki/LARPing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Letterboxing (hobby)','https://en.wikipedia.org/wiki/Letterboxing_(hobby)','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Longboarding','https://en.wikipedia.org/wiki/Longboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Martial arts','https://en.wikipedia.org/wiki/Martial_arts','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Metal detector','https://en.wikipedia.org/wiki/Metal_detector','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Meteorology','https://en.wikipedia.org/wiki/Meteorology','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Motor sports','https://en.wikipedia.org/wiki/Motor_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mountain biking','https://en.wikipedia.org/wiki/Mountain_biking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mountaineering','https://en.wikipedia.org/wiki/Mountaineering','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Museum','https://en.wikipedia.org/wiki/Museum','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mushroom hunting','https://en.wikipedia.org/wiki/Mushroom_hunting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mycology','https://en.wikipedia.org/wiki/Mycology','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Netball','https://en.wikipedia.org/wiki/Netball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Nordic skating','https://en.wikipedia.org/wiki/Nordic_skating','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Orienteering','https://en.wikipedia.org/wiki/Orienteering','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Paintball','https://en.wikipedia.org/wiki/Paintball','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Parkour','https://en.wikipedia.org/wiki/Parkour','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Photography','https://en.wikipedia.org/wiki/Photography','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Podcast','https://en.wikipedia.org/wiki/Podcast','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Polo','https://en.wikipedia.org/wiki/Polo','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Public transport','https://en.wikipedia.org/wiki/Public_transport','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rafting','https://en.wikipedia.org/wiki/Rafting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Railway','https://en.wikipedia.org/wiki/Railway','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rappelling','https://en.wikipedia.org/wiki/Rappelling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Road Cycling','https://en.wikipedia.org/wiki/Road_Cycling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rock climbing','https://en.wikipedia.org/wiki/Rock_climbing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Roller skating','https://en.wikipedia.org/wiki/Roller_skating','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rugby football','https://en.wikipedia.org/wiki/Rugby_football','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Running','https://en.wikipedia.org/wiki/Running','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Radio-controlled model','https://en.wikipedia.org/wiki/Radio-controlled_model','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sailing','https://en.wikipedia.org/wiki/Sailing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sand art and play','https://en.wikipedia.org/wiki/Sand_art_and_play','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Scouting','https://en.wikipedia.org/wiki/Scouting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Scuba diving','https://en.wikipedia.org/wiki/Scuba_diving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sculling','https://en.wikipedia.org/wiki/Sculling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rowing (sport)','https://en.wikipedia.org/wiki/Rowing_(sport)','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shooting','https://en.wikipedia.org/wiki/Shooting','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shopping','https://en.wikipedia.org/wiki/Shopping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shuffleboard','https://en.wikipedia.org/wiki/Shuffleboard','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Skateboarding','https://en.wikipedia.org/wiki/Skateboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Skiing','https://en.wikipedia.org/wiki/Skiing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Skimboarding','https://en.wikipedia.org/wiki/Skimboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Skydiving','https://en.wikipedia.org/wiki/Skydiving','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Slacklining','https://en.wikipedia.org/wiki/Slacklining','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Snowboarding','https://en.wikipedia.org/wiki/Snowboarding','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Snowmobiling','https://en.wikipedia.org/wiki/Snowmobiling','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Snowshoeing','https://en.wikipedia.org/wiki/Snowshoeing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Soccer','https://en.wikipedia.org/wiki/Soccer','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Stone skipping','https://en.wikipedia.org/wiki/Stone_skipping','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sun bathing','https://en.wikipedia.org/wiki/Sun_bathing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Surfing','https://en.wikipedia.org/wiki/Surfing','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Survivalism','https://en.wikipedia.org/wiki/Survivalism','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Human swimming','https://en.wikipedia.org/wiki/Human_swimming','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Taekwondo','https://en.wikipedia.org/wiki/Taekwondo','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tai chi','https://en.wikipedia.org/wiki/Tai_chi','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tennis','https://en.wikipedia.org/wiki/Tennis','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Topiary','https://en.wikipedia.org/wiki/Topiary','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tourism','https://en.wikipedia.org/wiki/Tourism','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Thru-hiking','https://en.wikipedia.org/wiki/Thru-hiking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Trade fair','https://en.wikipedia.org/wiki/Trade_fair','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Travel','https://en.wikipedia.org/wiki/Travel','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Urban exploration','https://en.wikipedia.org/wiki/Urban_exploration','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Vacation','https://en.wikipedia.org/wiki/Vacation','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Vegetable farming','https://en.wikipedia.org/wiki/Vegetable_farming','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Videography','https://en.wikipedia.org/wiki/Videography','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Vehicle restoration','https://en.wikipedia.org/wiki/Vehicle_restoration','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Walking','https://en.wikipedia.org/wiki/Walking','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Water sports','https://en.wikipedia.org/wiki/Water_sports','Ukategoriserede hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Astronomy','https://en.wikipedia.org/wiki/Astronomy','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Biology','https://en.wikipedia.org/wiki/Biology','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Chemistry','https://en.wikipedia.org/wiki/Chemistry','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Electrochemistry','https://en.wikipedia.org/wiki/Electrochemistry','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Geography','https://en.wikipedia.org/wiki/Geography','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'History','https://en.wikipedia.org/wiki/History','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mathematics','https://en.wikipedia.org/wiki/Mathematics','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Psychology','https://en.wikipedia.org/wiki/Psychology','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Physics','https://en.wikipedia.org/wiki/Physics','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rail transport','https://en.wikipedia.org/wiki/Rail_transport','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Science and technology studies','https://en.wikipedia.org/wiki/Science_and_technology_studies','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Social studies','https://en.wikipedia.org/wiki/Social_studies','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sports science','https://en.wikipedia.org/wiki/Sports_science','Educational hobbies','---');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Action figure','https://en.wikipedia.org/wiki/Action_figure','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Antiquing','https://en.wikipedia.org/wiki/Antiquing','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ant-keeping','https://en.wikipedia.org/wiki/Ant-keeping','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Art collecting','https://en.wikipedia.org/wiki/Art_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Book collecting','https://en.wikipedia.org/wiki/Book_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Button collecting','https://en.wikipedia.org/wiki/Button_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Trading cards','https://en.wikipedia.org/wiki/Trading_cards','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Coin collecting','https://en.wikipedia.org/wiki/Coin_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Comic book collecting','https://en.wikipedia.org/wiki/Comic_book_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Deltiology','https://en.wikipedia.org/wiki/Deltiology','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Die-cast toy','https://en.wikipedia.org/wiki/Die-cast_toy','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Digital hoarding','https://en.wikipedia.org/wiki/Digital_hoarding','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Dolls','https://en.wikipedia.org/wiki/Dolls','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Element collecting','https://en.wikipedia.org/wiki/Element_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ephemera','https://en.wikipedia.org/wiki/Ephemera','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Telephone card','https://en.wikipedia.org/wiki/Telephone_card','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Knife collecting','https://en.wikipedia.org/wiki/Knife_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Lotology','https://en.wikipedia.org/wiki/Lotology','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Film memorabilia','https://en.wikipedia.org/wiki/Film_memorabilia','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fingerprint','https://en.wikipedia.org/wiki/Fingerprint','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Perfume','https://en.wikipedia.org/wiki/Perfume','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Phillumeny','https://en.wikipedia.org/wiki/Phillumeny','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Radio-controlled model','https://en.wikipedia.org/wiki/Radio-controlled_model','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rail transport modelling','https://en.wikipedia.org/wiki/Rail_transport_modelling','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Record collecting','https://en.wikipedia.org/wiki/Record_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rock tumbling','https://en.wikipedia.org/wiki/Rock_tumbling','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Patch collecting','https://en.wikipedia.org/wiki/Patch_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shoes','https://en.wikipedia.org/wiki/Shoes','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Slot car','https://en.wikipedia.org/wiki/Slot_car','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sports memorabilia','https://en.wikipedia.org/wiki/Sports_memorabilia','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Stamp collecting','https://en.wikipedia.org/wiki/Stamp_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Stuffed toy','https://en.wikipedia.org/wiki/Stuffed_toy','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tea bag','https://en.wikipedia.org/wiki/Tea_bag','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ticket (admission)','https://en.wikipedia.org/wiki/Ticket_(admission)','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Toys','https://en.wikipedia.org/wiki/Toys','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Transit map','https://en.wikipedia.org/wiki/Transit_map','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Video game collecting','https://en.wikipedia.org/wiki/Video_game_collecting','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Vintage cars','https://en.wikipedia.org/wiki/Vintage_cars','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Vintage clothing','https://en.wikipedia.org/wiki/Vintage_clothing','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Vinyl Records','https://en.wikipedia.org/wiki/Vinyl_Records','Samler hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Antiquities','https://en.wikipedia.org/wiki/Antiquities','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Auto audiophilia','https://en.wikipedia.org/wiki/Auto_audiophilia','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pressed flower craft','https://en.wikipedia.org/wiki/Pressed_flower_craft','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fossil hunting','https://en.wikipedia.org/wiki/Fossil_hunting','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Insect collecting','https://en.wikipedia.org/wiki/Insect_collecting','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Magnet fishing','https://en.wikipedia.org/wiki/Magnet_fishing','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Metal detecting','https://en.wikipedia.org/wiki/Metal_detecting','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mineral collecting','https://en.wikipedia.org/wiki/Mineral_collecting','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rock balancing','https://en.wikipedia.org/wiki/Rock_balancing','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sea glass','https://en.wikipedia.org/wiki/Sea_glass','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Seashell','https://en.wikipedia.org/wiki/Seashell','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Stone collecting','https://en.wikipedia.org/wiki/Stone_collecting','Samler hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Animal fancy','https://en.wikipedia.org/wiki/Animal_fancy','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Axe throwing','https://en.wikipedia.org/wiki/Axe_throwing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Backgammon','https://en.wikipedia.org/wiki/Backgammon','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Badminton','https://en.wikipedia.org/wiki/Badminton','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Baton twirling','https://en.wikipedia.org/wiki/Baton_twirling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Beauty pageant','https://en.wikipedia.org/wiki/Beauty_pageant','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cue sports','https://en.wikipedia.org/wiki/Cue_sports','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Bowling','https://en.wikipedia.org/wiki/Bowling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Boxing','https://en.wikipedia.org/wiki/Boxing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Contract Bridge','https://en.wikipedia.org/wiki/Contract_Bridge','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Draughts','https://en.wikipedia.org/wiki/Draughts','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cheerleading','https://en.wikipedia.org/wiki/Cheerleading','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Chess','https://en.wikipedia.org/wiki/Chess','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Color guard (flag spinning)','https://en.wikipedia.org/wiki/Color_guard_(flag_spinning)','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cribbage','https://en.wikipedia.org/wiki/Cribbage','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Curling','https://en.wikipedia.org/wiki/Curling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Competitive dance','https://en.wikipedia.org/wiki/Competitive_dance','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Darts','https://en.wikipedia.org/wiki/Darts','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Debate','https://en.wikipedia.org/wiki/Debate','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Dominoes','https://en.wikipedia.org/wiki/Dominoes','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Competitive eating','https://en.wikipedia.org/wiki/Competitive_eating','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Esports','https://en.wikipedia.org/wiki/Esports','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fencing','https://en.wikipedia.org/wiki/Fencing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Go (game)','https://en.wikipedia.org/wiki/Go_(game)','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Gymnastics','https://en.wikipedia.org/wiki/Gymnastics','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ice hockey','https://en.wikipedia.org/wiki/Ice_hockey','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ice skating','https://en.wikipedia.org/wiki/Ice_skating','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Judo','https://en.wikipedia.org/wiki/Judo','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Jujitsu','https://en.wikipedia.org/wiki/Jujitsu','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Kabaddi','https://en.wikipedia.org/wiki/Kabaddi','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Word games','https://en.wikipedia.org/wiki/Word_games','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Laser tag','https://en.wikipedia.org/wiki/Laser_tag','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Longboarding','https://en.wikipedia.org/wiki/Longboarding','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Mahjong','https://en.wikipedia.org/wiki/Mahjong','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Marbles','https://en.wikipedia.org/wiki/Marbles','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Martial arts','https://en.wikipedia.org/wiki/Martial_arts','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Model United Nations','https://en.wikipedia.org/wiki/Model_United_Nations','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Poker','https://en.wikipedia.org/wiki/Poker','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pole Dancing (page does not exist)','https://en.wikipedia.org/w/index.php?title=Pole_Dancing&action=edit&redlink=1','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pool (cue sports)','https://en.wikipedia.org/wiki/Pool_(cue_sports)','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Role-playing games','https://en.wikipedia.org/wiki/Role-playing_games','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shogi','https://en.wikipedia.org/wiki/Shogi','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Slot car racing','https://en.wikipedia.org/wiki/Slot_car_racing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Speedcubing','https://en.wikipedia.org/wiki/Speedcubing','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sport stacking','https://en.wikipedia.org/wiki/Sport_stacking','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Table football','https://en.wikipedia.org/wiki/Table_football','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Table tennis','https://en.wikipedia.org/wiki/Table_tennis','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Volleyball','https://en.wikipedia.org/wiki/Volleyball','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Weight training','https://en.wikipedia.org/wiki/Weight_training','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Wrestling','https://en.wikipedia.org/wiki/Wrestling','Konkurrence hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Airsoft','https://en.wikipedia.org/wiki/Airsoft','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Archery','https://en.wikipedia.org/wiki/Archery','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Association football','https://en.wikipedia.org/wiki/Association_football','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Australian rules football','https://en.wikipedia.org/wiki/Australian_rules_football','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Auto racing','https://en.wikipedia.org/wiki/Auto_racing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Baseball','https://en.wikipedia.org/wiki/Baseball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Beach volleyball','https://en.wikipedia.org/wiki/Beach_volleyball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Breakdancing','https://en.wikipedia.org/wiki/Breakdancing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Climbing','https://en.wikipedia.org/wiki/Climbing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cricket','https://en.wikipedia.org/wiki/Cricket','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Croquet','https://en.wikipedia.org/wiki/Croquet','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Cycling','https://en.wikipedia.org/wiki/Cycling','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Disc golf','https://en.wikipedia.org/wiki/Disc_golf','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Dog sport','https://en.wikipedia.org/wiki/Dog_sport','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Equestrianism','https://en.wikipedia.org/wiki/Equestrianism','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Exhibition drill','https://en.wikipedia.org/wiki/Exhibition_drill','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Field hockey','https://en.wikipedia.org/wiki/Field_hockey','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Figure skating','https://en.wikipedia.org/wiki/Figure_skating','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fishing','https://en.wikipedia.org/wiki/Fishing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Footbag','https://en.wikipedia.org/wiki/Footbag','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Frisbee','https://en.wikipedia.org/wiki/Frisbee','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Golf','https://en.wikipedia.org/wiki/Golf','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Handball','https://en.wikipedia.org/wiki/Handball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Horseback riding','https://en.wikipedia.org/wiki/Horseback_riding','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Horseshoes','https://en.wikipedia.org/wiki/Horseshoes','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Iceboat','https://en.wikipedia.org/wiki/Iceboat','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Jukskei','https://en.wikipedia.org/wiki/Jukskei','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Kart racing','https://en.wikipedia.org/wiki/Kart_racing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Knife throwing','https://en.wikipedia.org/wiki/Knife_throwing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Lacrosse','https://en.wikipedia.org/wiki/Lacrosse','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Longboarding','https://en.wikipedia.org/wiki/Longboarding','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Long-distance running','https://en.wikipedia.org/wiki/Long-distance_running','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Marching band','https://en.wikipedia.org/wiki/Marching_band','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Model aircraft','https://en.wikipedia.org/wiki/Model_aircraft','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Orienteering','https://en.wikipedia.org/wiki/Orienteering','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Pickleball','https://en.wikipedia.org/wiki/Pickleball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Quidditch (sport)','https://en.wikipedia.org/wiki/Quidditch_(sport)','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Race walking','https://en.wikipedia.org/wiki/Race_walking','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Racquetball','https://en.wikipedia.org/wiki/Racquetball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Radio-controlled car','https://en.wikipedia.org/wiki/Radio-controlled_car','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Roller derby','https://en.wikipedia.org/wiki/Roller_derby','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rugby league','https://en.wikipedia.org/wiki/Rugby_league','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sculling','https://en.wikipedia.org/wiki/Sculling','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Rowing','https://en.wikipedia.org/wiki/Rowing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shooting sport','https://en.wikipedia.org/wiki/Shooting_sport','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Skateboarding','https://en.wikipedia.org/wiki/Skateboarding','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Skiing','https://en.wikipedia.org/wiki/Skiing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Sled dog racing','https://en.wikipedia.org/wiki/Sled_dog_racing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Softball','https://en.wikipedia.org/wiki/Softball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Speed skating','https://en.wikipedia.org/wiki/Speed_skating','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Squash (sport)','https://en.wikipedia.org/wiki/Squash_(sport)','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Surfing','https://en.wikipedia.org/wiki/Surfing','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Human swimming','https://en.wikipedia.org/wiki/Human_swimming','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Table tennis','https://en.wikipedia.org/wiki/Table_tennis','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tennis','https://en.wikipedia.org/wiki/Tennis','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tennis polo','https://en.wikipedia.org/wiki/Tennis_polo','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tether car','https://en.wikipedia.org/wiki/Tether_car','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tour skating','https://en.wikipedia.org/wiki/Tour_skating','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Tourism','https://en.wikipedia.org/wiki/Tourism','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Trapshooting','https://en.wikipedia.org/wiki/Trapshooting','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Triathlon','https://en.wikipedia.org/wiki/Triathlon','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Ultimate (sport)','https://en.wikipedia.org/wiki/Ultimate_(sport)','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Volleyball','https://en.wikipedia.org/wiki/Volleyball','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Water polo','https://en.wikipedia.org/wiki/Water_polo','Konkurrence hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Fishkeeping','https://en.wikipedia.org/wiki/Fishkeeping',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Learning','https://en.wikipedia.org/wiki/Learning',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Meditation','https://en.wikipedia.org/wiki/Meditation',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Microscopy','https://en.wikipedia.org/wiki/Microscopy',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Reading','https://en.wikipedia.org/wiki/Reading',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Research','https://en.wikipedia.org/wiki/Research',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Shortwave listening','https://en.wikipedia.org/wiki/Shortwave_listening',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Audiophile','https://en.wikipedia.org/wiki/Audiophile',' Observation hobbyer','Indendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Aircraft spotting','https://en.wikipedia.org/wiki/Aircraft_spotting',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Amateur astronomy','https://en.wikipedia.org/wiki/Amateur_astronomy',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Birdwatching','https://en.wikipedia.org/wiki/Birdwatching',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Bus spotting','https://en.wikipedia.org/wiki/Bus_spotting',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Geocaching','https://en.wikipedia.org/wiki/Geocaching',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Gongoozler','https://en.wikipedia.org/wiki/Gongoozler',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Herping','https://en.wikipedia.org/wiki/Herping',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Hiking','https://en.wikipedia.org/wiki/Hiking',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Backpacking (wilderness)','https://en.wikipedia.org/wiki/Backpacking_(wilderness)',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Meteorology','https://en.wikipedia.org/wiki/Meteorology',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Photography','https://en.wikipedia.org/wiki/Photography',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Satellite watching','https://en.wikipedia.org/wiki/Satellite_watching',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Trainspotting (hobby)','https://en.wikipedia.org/wiki/Trainspotting_(hobby)',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Whale watching','https://en.wikipedia.org/wiki/Whale_watching',' Observation hobbyer','Udendørs');
INSERT INTO hobby (id,name,description,category,environment)VALUES (null,'Whale watching','https://en.wikipedia.org/wiki/Whale_watching',' Observation hobbyer','Udendørs2');

 */